project:
  type: website

profile:
  default: english
  group: [english, french]

format:
  html:
    theme: 
      light: flatly
      dark: darkly

website:
  search: false

  cookie-consent:
    type: implied
    style: simple
  google-analytics: 
    tracking-id: "G-7324YQTBH0"