project:
  title: "Vincent Grégoire, Ph.D."
  output-dir: ./_site/fr

website:
  description: "Vincent Grégoire, Ph.D. Professeur de finance à HEC Montréal"
  twitter-card: true
  open-graph:
    locale: fr_CA
    site-name: "Vincent Grégoire, Ph.D."
  site-url: https://www.vincentgregoire.com/fr
  page-footer: 
    left: "Tous droits réservés. Vincent Grégoire 2024" 
  navbar:
    left:
      - href: research.qmd
        text: Recherche
      - href: students.qmd
        text: Étudiants
      - href: code.qmd
        text: Code
      - href: ../CV_Gregoire.pdf
        text: CV
      - href: https://vincent.codes.finance
        text: Blog
      - href: https://www.youtube.com/channel/UCuNrwdpvF1LBGJ2cNL5b68w
        text: YouTube
    right:
      - href: ../
        text: English
lang: fr

