
::: {.content-visible when-profile="english"}

# Code

My publicly available code is distributed through [GitHub](https://github.com/vgreg). You can also find some of my tutorials on my blog, [Vincent Codes Finance](https://vincent.codes.finance).

## Select Projects

- [MeatPy](https://github.com/vgreg/MeatPy)  
  Market Empirical Analysis Toolbox for Python. The goal of this project is to provide a standard framework for processing and analysing high-frequency limit order book data.
- [Price Revelation from Insider Trading: Evidence from Hacked Earnings News](https://github.com/vgreg/hacked_earnings_jfe)  
  Code from the paper _Price Revelation from Insider Trading: Evidence from Hacked Earnings News_, **Journal of Financial Economics**, Volume 143, Issue 3, 2022.
- [How is Earnings News Transmitted to Stock Prices?](https://github.com/vgreg/earnings_news_jar)  
  Code from the paper _How is Earnings News Transmitted to Stock Prices?_ **Journal of Accounting Research**, Volume 60, Issue 1, 2022.


:::


::: {.content-visible when-profile="french"}

# Code

Mon code public est disponible sur [GitHub](https://github.com/vgreg). Vous pouvez également trouver certains de mes tutoriels sur mon blog, [Vincent Codes Finance](https://vincent.codes.finance).

## Projets en vedette

- [MeatPy](https://github.com/vgreg/MeatPy)  
  Market Empirical Analysis Toolbox for Python. L'objectif de ce projet est de fournir un code standard pour le traitement et l'analyse des données à haute fréquence d'un carnet d'ordres.
- [Price Revelation from Insider Trading: Evidence from Hacked Earnings News](https://github.com/vgreg/hacked_earnings_jfe)  
  Code pour l'article _Price Revelation from Insider Trading: Evidence from Hacked Earnings News_, **Journal of Financial Economics**, Volume 143, Issue 3, 2022.
- [How is Earnings News Transmitted to Stock Prices?](https://github.com/vgreg/earnings_news_jar)  
  Code pour l'article _How is Earnings News Transmitted to Stock Prices?_ **Journal of Accounting Research**, Volume 60, Issue 1, 2022.

:::
