

::: {.content-visible when-profile="english"}

# Research

## Working Papers

- **Noisy FOMC Returns: Information, Price Pressure, and Post-Announcement Reversals**  
   with [Oliver Boguth](http://www.public.asu.edu/~oboguth/), [Adlai Fisher](https://sites.google.com/view/adlai-fisher), and [Charles Martineau](http://www.charlesmartineau.com)  
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4131740)]

  - Best Paper on Asset Pricing Award, NFA 2022

- **Double Bonus? Implicit Incentives for Money Managers with Explicit Incentives**  
   with [Juan Sotes-Paladino](https://sites.google.com/site/jmsotespaladino/home)  
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2980599)]

## Publications

- **Price Revelation from Insider Trading: Evidence from Hacked Earnings News**  
  _Journal of Financial Economics_, Volume 143, Issue 3, 2022,  
   with [Pat Akey](http://patakeyfinance.com) and [Charles Martineau](http://www.charlesmartineau.com),  
  [[JFE <i class="ai ai-open-access ai-fw "></i>](https://doi.org/10.1016/j.jfineco.2021.12.006)]
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3365024)]
  [[Code <i class="fab fa-fw fa-github" aria-hidden="true"></i>](https://github.com/vgreg/hacked_earnings_jfe)]

  - [Article on Bloomberg.com](https://www.bloomberg.com/news/articles/2019-04-22/the-market-knew-about-the-press-release-hackers-before-the-cops), 2019
  - [Article on Columbia Law’s Blue Sky blog](http://clsbluesky.law.columbia.edu/2019/07/10/price-revelation-from-insider-trading-evidence-from-hacked-earnings-news/), 2019

- **How is Earnings News Transmitted to Stock Prices?**  
  _Journal of Accounting Research_, Volume 60, Issue 1, 2022,  
   with [Charles Martineau](http://www.charlesmartineau.com),  
  [[JAR <i class="ai ai-open-access ai-fw "></i>](https://doi.org/10.1111/1475-679X.12394)]
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3060094)]
  [[Code <i class="fab fa-fw fa-github" aria-hidden="true"></i>](https://github.com/vgreg/earnings_news_jar)]

- **Inverted Fee Structures, Tick Size, and Market Quality**  
  _Journal of Financial Economics_, Volume 134, Issue 1, 2019,  
   with [Carole Comerton-Forde](https://fbe.unimelb.edu.au/our-people/staff/finance/carole-comerton-forde2) and [Zhuo Zhong](http://www.joe-zh.com/),  
   [[JFE](https://doi.org/10.1016/j.jfineco.2019.03.005)]
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2939012)]
  [[Online Appendix](/files/appendices/adf-tsp-appendix.pdf)]

  - Best Paper on Market Microstructure Award, NFA 2017

- **Shaping Expectations and Coordinating Attention: The Unintended Consequences of FOMC Press Conferences**  
  _Journal of Financial and Quantitative Analysis_, Volume 54, Issue 6, 2019,  
  with [Oliver Boguth](http://www.public.asu.edu/~oboguth/) and [Charles Martineau](http://www.charlesmartineau.com),  
  [[JFQA](https://doi.org/10.1017/S0022109018001357)]
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2698477)]
  [[Internet Appendix](/files/appendices/FOMC_PC_InternetAppendix.pdf)]

  **Note**: Since January 2019, the Chairman of the Federal Reserve now holds a press conference after each meeting, which is the main policy recommendation of the paper. A postscript at the end of the paper addresses this point.

  - Best Paper on Financial Institutions and Markets Award, 7th Financial Markets and Corporate Governance Conference (2016)
  - [Article in The Globe and Mail](https://www.theglobeandmail.com/business/careers/business-education/article-greater-transparency-in-business-can-have-unintended-consequences/), 2019
  - Live interview with Sky Business News, 2015
  - [Mention in LA Times](http://www.latimes.com/business/la-fi-yellen-hike-analysis-20151216-story.html/), 2015

- **The Rise of Passive Investing and Index-linked Comovement**  
  _North American Journal of Economics and Finance_, Volume 51, 101059, 2020,  
  [[NAJEF](https://doi.org/10.1016/j.najef.2019.101059)]
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2308695)]
  [[Internet Appendix](/files/appendices/indexers_appendix.pdf)]

## Supervised Student Work


- **Circular Economy: A Fintech Driven Solution for Sustainable Practices** (book chapter)  
  In [Fintech and Sustainability:
How Financial Technologies Can Help Address Today's Environmental and Societal Challenges](https://link.springer.com/book/10.1007/978-3-031-40647-8), Palgrave Macmillan, pp. 149-168, 2023,  
  with [Kevin Guay](https://www.linkedin.com/in/kevin-guay/),  
  [[Springer](https://link.springer.com/chapter/10.1007/978-3-031-40647-8_8)]


- **HFTViz: Visualization for the exploration of high frequency trading data**  
  _Information Visualization_, Volume 21, Issue 2, 2022,  
  with [Javad Yaali](https://www.linkedin.com/in/javadyaali/) and [Thomas Hurtut](http://www.professeurs.polymtl.ca/thomas.hurtut/),  
  [[InfoVis <i class="ai ai-open-access ai-fw "></i>](https://doi.org/10.1177/14738716211064921)]

- **Alternative Data** (book chapter)  
  In [Big Data in Finance: Opportunities and Challenges of Financial Digitalization](https://link.springer.com/book/10.1007/978-3-031-12240-8), Palgrave Macmillan, pp. 13-33, 2022,  
  with [Noah Jepson](https://www.linkedin.com/in/noahjep/),  
  [[Springer](https://link.springer.com/chapter/10.1007/978-3-031-12240-8_2)]

## Other Research Contributions

- **Non-Standard Errors**  
  Forthcoming in _Journal of Finance_,  
  coordinated by [Albert J. Menkveld](https://albertjmenkveld.com/), [Anna Dreber](https://sites.google.com/site/annadreber/), [Felix Holzmeister](https://www.holzmeister.biz/), [Juergen Huber](https://www.uibk.ac.at/ibf/team/huberj.html.en), [Magnus Johannesson](https://www.hhs.se/en/persons/j/johannesson-magnus/), [Michael Kirchler](https://www.uibk.ac.at/ibf/team/kirchler.html.en), [Michael Razen](https://www.uibk.ac.at/ibf/mitarbeiter/razen.html), and [Utz Weitzel](https://research.vu.nl/en/persons/utz-weitzel). (300+ co-authors)  
  [[SSRN](https://dx.doi.org/10.2139/ssrn.3961574)]

  - I was part of a team that was responsible for doing the data analysis and writing a summary paper. Our _paper_ was one of the five best rated papers that were shared with all the teams in the last phase of the project. Our code is available [on GitHub](https://github.com/vgreg/fincap).

## Forever Working Papers

- Do Mutual Fund Managers Adjust NAV for Stale Prices?  
[[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1928321)]

## Pre-PhD Publications

- **Using copulas to model price dependence in energy markets**  
  _Energy risk_, Volume 5, Issue 5, 2008,  
   with [Christian Genest](https://www.math.mcgill.ca/cgenest/) and Michel Gendron,  
   [[CiteSeerX](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.461.3276&rep=rep1&type=pdf)]

- **Visible and infrared imagery for surveillance applications: software and hardware considerations**  
  _Quantitative InfraRed Thermography Journal_, Volume 4, Issue 1, 2007,  
   with Amar El-Maadi, Louis St-Laurent, Hélène Torresan, Benoit Turgeon, Donald Prévost, Patrick Hébert, Denis Laurendeau, Benoit Ricard and Xavier Maldague,  
   [[Taylor & Francis](https://doi.org/10.3166/qirt.4.25-40)]

:::


::: {.content-visible when-profile="french"}

# Recherche

## Documents de travail

- **Noisy FOMC Returns: Information, Price Pressure, and Post-Announcement Reversals**  
   avec [Oliver Boguth](http://www.public.asu.edu/~oboguth/), [Adlai Fisher](https://sites.google.com/view/adlai-fisher) et [Charles Martineau](http://www.charlesmartineau.com)  
    [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4131740)]

  - Best Paper on Asset Pricing Award, NFA 2022

- **Double Bonus? Implicit Incentives for Money Managers with Explicit Incentives**  
   avec [Juan Sotes-Paladino](https://sites.google.com/site/jmsotespaladino/home)  
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2980599)]

## Publications

- **Price Revelation from Insider Trading: Evidence from Hacked Earnings News**  
  _Journal of Financial Economics_, Volume 143, Issue 3, 2022,  
   avec [Pat Akey](http://patakeyfinance.com) et [Charles Martineau](http://www.charlesmartineau.com),  
  [[JFE <i class="ai ai-open-access ai-fw "></i>](https://doi.org/10.1016/j.jfineco.2021.12.006)]
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3365024)]
  [[Code <i class="fab fa-fw fa-github" aria-hidden="true"></i>](https://github.com/vgreg/hacked_earnings_jfe)]

  - [Article sur Bloomberg.com](https://www.bloomberg.com/news/articles/2019-04-22/the-market-knew-about-the-press-release-hackers-before-the-cops), 2019
  - [Article sur Columbia Law’s Blue Sky blog](http://clsbluesky.law.columbia.edu/2019/07/10/price-revelation-from-insider-trading-evidence-from-hacked-earnings-news/), 2019

- **How is Earnings News Transmitted to Stock Prices?**  
  _Journal of Accounting Research_, Volume 60, Issue 1, 2022,  
   avec [Charles Martineau](http://www.charlesmartineau.com),  
  [[JAR <i class="ai ai-open-access ai-fw "></i>](https://doi.org/10.1111/1475-679X.12394)]
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3060094)]
  [[Code <i class="fab fa-fw fa-github" aria-hidden="true"></i>](https://github.com/vgreg/earnings_news_jar)]

- **Inverted Fee Structures, Tick Size, and Market Quality**  
  _Journal of Financial Economics_, Volume 134, Issue 1, 2019,  
   avec [Carole Comerton-Forde](https://fbe.unimelb.edu.au/our-people/staff/finance/carole-comerton-forde2) et [Zhuo Zhong](http://www.joe-zh.com/),  
   [[JFE](https://doi.org/10.1016/j.jfineco.2019.03.005)]
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2939012)]
  [[Online Appendix](/files/appendices/adf-tsp-appendix.pdf)]

  - Best Paper on Market Microstructure Award, NFA 2017

- **Shaping Expectations and Coordinating Attention: The Unintended Consequences of FOMC Press Conferences**  
  _Journal of Financial and Quantitative Analysis_, Volume 54, Issue 6, 2019,  
  avec [Oliver Boguth](http://www.public.asu.edu/~oboguth/) et [Charles Martineau](http://www.charlesmartineau.com),  
  [[JFQA](https://doi.org/10.1017/S0022109018001357)]
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2698477)]
  [[Internet Appendix](/files/appendices/FOMC_PC_InternetAppendix.pdf)]

  **Note**: Depuis janvier 2019, le président de la Réserve fédérale tient désormais une conférence de presse après chaque réunion, qui est la principale recommandation politique de l'article. Un post-scriptum à la fin de l'article aborde ce point.

  - Best Paper on Financial Institutions and Markets Award, 7th Financial Markets and Corporate Governance Conference (2016)
  - [Article dans The Globe and Mail](https://www.theglobeandmail.com/business/careers/business-education/article-greater-transparency-in-business-can-have-unintended-consequences/), 2019
  - Entrevue en direct avec Sky Business News, 2015
  - [Mention dans le LA Times](http://www.latimes.com/business/la-fi-yellen-hike-analysis-20151216-story.html/), 2015

- **The Rise of Passive Investing and Index-linked Comovement**  
  _North American Journal of Economics and Finance_, Volume 51, 101059, 2020,  
  [[NAJEF](https://doi.org/10.1016/j.najef.2019.101059)]
  [[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2308695)]
  [[Internet Appendix](/files/appendices/indexers_appendix.pdf)]

## Travaux étudiants supervisés

- **Circular Economy: A Fintech Driven Solution for Sustainable Practices** (chapitre de livre)  
  Dans [Fintech and Sustainability:
How Financial Technologies Can Help Address Today's Environmental and Societal Challenges](https://link.springer.com/book/10.1007/978-3-031-40647-8), Palgrave Macmillan, pp. 149-168, 2023,  
  avec [Kevin Guay](https://www.linkedin.com/in/kevin-guay/),  
  [[Springer](https://link.springer.com/chapter/10.1007/978-3-031-40647-8_8)]

- **HFTViz: Visualization for the exploration of high frequency trading data**
  _Information Visualization_, Volume 21, Issue 2, 2022,  
  avec Javad Yaali et [Thomas Hurtut](http://www.professeurs.polymtl.ca/thomas.hurtut/),  
  [[InfoVis <i class="ai ai-open-access ai-fw "></i>](https://doi.org/10.1177/14738716211064921)]

- **Alternative Data** (chapitre de livre)  
  Dans [Big Data in Finance: Opportunities and Challenges of Financial Digitalization](https://link.springer.com/book/10.1007/978-3-031-12240-8), Palgrave Macmillan, pp. 13-33, 2022,  
  avec [Noah Jepson](https://www.linkedin.com/in/noahjep/),  
  [[Springer](https://link.springer.com/chapter/10.1007/978-3-031-12240-8_2)]

## Autres contributions à la recherche

- **Non-Standard Errors**  
  À paraître dans _Journal of Finance_,
  coordonné par [Albert J. Menkveld](https://albertjmenkveld.com/), [Anna Dreber](https://sites.google.com/site/annadreber/), [Felix Holzmeister](https://www.holzmeister.biz/), [Juergen Huber](https://www.uibk.ac.at/ibf/team/huberj.html.en), [Magnus Johannesson](https://www.hhs.se/en/persons/j/johannesson-magnus/), [Michael Kirchler](https://www.uibk.ac.at/ibf/team/kirchler.html.en), [Michael Razen](https://www.uibk.ac.at/ibf/mitarbeiter/razen.html), et [Utz Weitzel](https://research.vu.nl/en/persons/utz-weitzel). (300+ co-auteurs)  
  [[SSRN](https://dx.doi.org/10.2139/ssrn.3961574)]

  - J'ai fait partie d'une équipe responsable de l'analyse des données et de la rédaction d'un article résumé. Notre _article_ était l'un des cinq meilleurs articles évalués qui ont été partagés avec toutes les équipes lors de la dernière phase du projet. Notre code est disponible [sur GitHub](https://github.com/vgreg/fincap).

## Documents de travail permanents

- Do Mutual Fund Managers Adjust NAV for Stale Prices?  
[[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1928321)]

## Publications pré-doctorat

- **Using copulas to model price dependence in energy markets**  
  _Energy risk_, Volume 5, Issue 5, 2008,  
   avec [Christian Genest](https://www.math.mcgill.ca/cgenest/) et Michel Gendron,  
   [[CiteSeerX](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.461.3276&rep=rep1&type=pdf)]

- **Visible and infrared imagery for surveillance applications: software and hardware considerations**  
  _Quantitative InfraRed Thermography Journal_, Volume 4, Issue 1, 2007,  
   avec Amar El-Maadi, Louis St-Laurent, Hélène Torresan, Benoit Turgeon, Donald Prévost, Patrick Hébert, Denis Laurendeau, Benoit Ricard et Xavier Maldague,  
   [[Taylor & Francis](https://doi.org/10.3166/qirt.4.25-40)]

:::