
::: {.content-visible when-profile="english"}

# Students

## Prospective students

### PhD

Admissions for admission in September 2025 are now closed. I will update this page when admissions for September 2026 are open.

### MSc students already enrolled at HEC Montéal

If you are interested in working under my supervision for your MSc thesis or supervised project, please contact me by [email](mailto:vincent.gregoire@hec.ca?subject="Supervision"). The initial email requesting supervision for a supervised project or thesis should include the following elements:

- If it is for a thesis or supervised project, and for a supervised project if it is to be done with an industry partner.
- Expected start and completion date of your project.
- A list of topics of interest to you or potential research questions.

Note that I am often overbooked for supervision. I will either try to book a meeting with you to discuss your project further or recommend other professors in line with your topics of interest.

For MSc students **not** already enrolled at HEC Montréal, please see the [MSc program page](https://www.hec.ca/en/programs/masters/master-finance/index.html).

## Current students

### MSc

- [Khashayar Badiee](https://www.linkedin.com/in/khashayar-badiee-39b456145/)
- [Manon Chevanne](https://www.linkedin.com/in/manon-chevanne/)
- [Zahra Hashemi](https://www.linkedin.com/in/zahra-hashemi-400a3a159/), funded by [Fin-ML](https://fin-ml.ca/)
- [Parsa Moaven](https://www.linkedin.com/in/parsa-moaven/)
- [Daphné Phuong Thi Binard](https://www.linkedin.com/in/daphn%C3%A9-binard-769618149/)

## Past students

### MSc - HEC Montréal

- **2024**
  - [Mohammad Ebrahimi](https://www.linkedin.com/in/3moheb/), co-supervised with [Simon van Norden](https://www.hec.ca/en/profs/simon.van-norden.html), funded by [Fin-ML](https://fin-ml.ca/)
  - [Nicolas Frenette](https://www.linkedin.com/in/nicolasfrenette/)
  - [Mathieu Haché](https://www.linkedin.com/in/hachemathieu/)
  - [Bell Jotio](https://www.linkedin.com/in/bell-jotio-7a0100160/), funded by [Fin-ML](https://fin-ml.ca/)

- **2023**
  - [Alireza Fallahi](https://www.linkedin.com/in/alireza-fallahii/), co-supervised with [Saad Ali Khan](http://saadalikhan.com/)
  - [Alec Gauthier](https://www.linkedin.com/in/alecgauthier/)
  - [Kevin Guay](https://www.linkedin.com/in/kevin-guay/)
  - [Nicolas Harvie](https://www.linkedin.com/in/nicolas-harvie-a49972135/), co-supervised with [Anthony Sanford](https://www.anthonysanford.com/)
  - [Yasmin Kalhor](https://www.linkedin.com/in/yasmin-kalhor/), co-supervised with [Charles Martineau](http://www.charlesmartineau.com)
  - [Amin Moeinian](https://www.linkedin.com/in/aminmoeinian/), co-supervised with [Tolga Cenesizoglu](https://www.hec.ca/en/profs/tolga.cenesizoglu.html)
  - [Samuel Lopez](https://www.linkedin.com/in/samuel-lopez-/)
  - [Clément Markus](https://www.linkedin.com/in/clement-markus/), co-supervised with [Tolga Cenesizoglu](https://www.hec.ca/en/profs/tolga.cenesizoglu.html)
  - Yutong Qin, co-supervised with [Tolga Cenesizoglu](https://www.hec.ca/en/profs/tolga.cenesizoglu.html)
- **2022**
  - [Tarek Berrahal](https://www.linkedin.com/in/tarekberrahal/), partially funded by the [Chaire Fintech AMF – Finance Montréal](https://chairefintech.uqam.ca/?lang=en)
  - [Vincent Boucher](https://www.linkedin.com/in/bouchervincent/), co-supervised with [Iwan Meier](https://www.hec.ca/en/profs/iwan.meier.html)
  - [Sormeh Dolati](https://www.linkedin.com/in/sormeh-dolati/)
  - [Elliott Francoeur](https://www.linkedin.com/in/elliott-francoeur/)
  - [Noah Jepson](https://www.linkedin.com/in/noahjep/)
  - [Natali Yerokhina Mazer](https://www.linkedin.com/in/natali-yerokhina-mazer-48542b1b0/), co-supervised with [Tolga Cenesizoglu](https://www.hec.ca/en/profs/tolga.cenesizoglu.html)
  - [Yue Wu](https://www.linkedin.com/in/yue-w-73257214a/)
  - [Yilin Zhang](https://www.linkedin.com/in/yilin-zhang-/), co-supervised with [Charles Martineau](http://www.charlesmartineau.com)
- **2021**
  - [Vincent Ouellet](https://www.linkedin.com/in/vincentouellet/)
- **2020**
  - [Alexandre Claveau](https://www.linkedin.com/in/alexandre-claveau-m-sc-52b513170/), partially funded by the [Chaire Fintech AMF – Finance Montréal](https://chairefintech.uqam.ca/?lang=en)
  - [Rajat Kumar](https://www.linkedin.com/in/rajatkumar376/), co-supervised with [Tolga Cenesizoglu](https://www.hec.ca/en/profs/tolga.cenesizoglu.html)
  - [Philip Marceau](https://www.linkedin.com/in/philip-marceau-753b8a1b3/)

### Honours - Univesity of Melbourne

- **2016**
  - Xinyi Shi
- **2015**
  - [Yukun (Daniel) Luo](https://www.linkedin.com/in/daniel-luo-9676b855/)
- **2014**
  - [Hamish Cruden](https://www.linkedin.com/in/hamishcruden/)


:::



::: {.content-visible when-profile="french"}

# Étudiants


## Futurs étudiants

### Doctorat

Les admissions pour l'année académique 2025-2026 sont désormais fermées. Je mettrai à jour cette page lorsque les admissions pour l'année académique 2026-2027 seront ouvertes.

### Étudiants de maîtrise déjà inscrits à HEC Montréal

Si vous êtes intéressé à travailler sous ma supervision pour votre mémoire ou projet supervisé, veuillez me contacter par [courriel](mailto:vincent.gregoire@hec.ca?subject="Supervision"). Le courriel initial de demande de supervision pour un mémoire ou projet supervisé doit inclure les éléments suivants :

- S'il s'agit d'une thèse ou d'un projet supervisé, et pour un projet supervisé s'il est à réaliser avec un partenaire industriel.
- Date prévue de début et de fin de votre projet.
- Une liste de sujets qui vous intéressent ou de questions de recherche potentielles.

Notez que je suis souvent à pleine capacité pour la supervision. J'essaierai soit de prendre rendez-vous avec vous pour discuter plus en détail de votre projet, soit de recommander d'autres professeurs en rapport avec vos sujets d'intérêt.

Pour les étudiants de maîtrise **non** déjà inscrits à HEC Montréal, veuillez consulter la [page du programme de maîtrise](https://www.hec.ca/programmes/maitrises/maitrise-finance/index.html).

## Étudiants actuels

### Maîtrise

- [Khashayar Badiee](https://www.linkedin.com/in/khashayar-badiee-39b456145/)
- [Manon Chevanne](https://www.linkedin.com/in/manon-chevanne/)
- [Zahra Hashemi](https://www.linkedin.com/in/zahra-hashemi-400a3a159/), financée par [Fin-ML](https://fin-ml.ca/)
- [Parsa Moaven](https://www.linkedin.com/in/parsa-moaven/)
- [Daphné Phuong Thi Binard](https://www.linkedin.com/in/daphn%C3%A9-binard-769618149/)

## Étudiants passés

### Maîtrise - HEC Montréal

- **2024**
 - [Mohammad Ebrahimi](https://www.linkedin.com/in/3moheb/), co-supervision avec [Simon van Norden](https://www.hec.ca/profs/simon.van-norden.html), financé par [Fin-ML](https://fin-ml.ca/)
  - [Nicolas Frenette](https://www.linkedin.com/in/nicolasfrenette/)
  - [Mathieu Haché](https://www.linkedin.com/in/hachemathieu/)
  - [Bell Jotio](https://www.linkedin.com/in/bell-jotio-7a0100160/), financé par [Fin-ML](https://fin-ml.ca/)
- **2023**
  - [Alireza Fallahi](https://www.linkedin.com/in/alireza-fallahii/), co-supervision avec [Saad Ali Khan](http://saadalikhan.com/)
  - [Alec Gauthier](https://www.linkedin.com/in/alecgauthier/)
  - [Kevin Guay](https://www.linkedin.com/in/kevin-guay/)
  - [Nicolas Harvie](https://www.linkedin.com/in/nicolas-harvie-a49972135/), co-supervision avec [Anthony Sanford](https://www.anthonysanford.com/)
  - [Yasmin Kalhor](https://www.linkedin.com/in/yasmin-kalhor/), co-supervision avec [Charles Martineau](http://www.charlesmartineau.com)- [Amin Moeinian](https://www.linkedin.com/in/aminmoeinian/), co-supervision avec [Tolga Cenesizoglu](https://www.hec.ca/profs/tolga.cenesizoglu.html)
  - [Samuel Lopez](https://www.linkedin.com/in/samuel-lopez-/)
  - [Clément Markus](https://www.linkedin.com/in/clement-markus/), co-supervision avec [Tolga Cenesizoglu](https://www.hec.ca/profs/tolga.cenesizoglu.html)
  - Yutong Qin, co-supervision avec [Tolga Cenesizoglu](https://www.hec.ca/profs/tolga.cenesizoglu.html)
- **2022**
  - [Tarek Berrahal](https://www.linkedin.com/in/tarekberrahal/), financé en partie par la [Chaire Fintech AMF – Finance Montréal](https://chairefintech.uqam.ca/)
  - [Vincent Boucher](https://www.linkedin.com/in/bouchervincent/), co-supervision avec [Iwan Meier](https://www.hec.ca/profs/iwan.meier.html)
  - [Sormeh Dolati](https://www.linkedin.com/in/sormeh-dolati/)
  - [Elliott Francoeur](https://www.linkedin.com/in/elliott-francoeur/)
  - [Noah Jepson](https://www.linkedin.com/in/noahjep/)
  - [Natali Yerokhina Mazer](https://www.linkedin.com/in/natali-yerokhina-mazer-48542b1b0/), co-supervision avec [Tolga Cenesizoglu](https://www.hec.ca/profs/tolga.cenesizoglu.html)
  - [Yue Wu](https://www.linkedin.com/in/yue-w-73257214a/)
  - [Yilin Zhang](https://www.linkedin.com/in/yilin-zhang-/), co-supervision avec [Charles Martineau](http://www.charlesmartineau.com)
- **2021**
  - [Vincent Ouellet](https://www.linkedin.com/in/vincentouellet/)
- **2020**
  - [Alexandre Claveau](https://www.linkedin.com/in/alexandre-claveau-m-sc-52b513170/), financé en partie par la [Chaire Fintech AMF – Finance Montréal](https://chairefintech.uqam.ca/)
  - [Rajat Kumar](https://www.linkedin.com/in/rajatkumar376/), co-supervision avec [Tolga Cenesizoglu](https://www.hec.ca/profs/tolga.cenesizoglu.html)
  - [Philip Marceau](https://www.linkedin.com/in/philip-marceau-753b8a1b3/)

### Honours - University of Melbourne

- **2016**
  - Xinyi Shi
- **2015**
  - [Yukun (Daniel) Luo](https://www.linkedin.com/in/daniel-luo-9676b855/)
- **2014**
  - [Hamish Cruden](https://www.linkedin.com/in/hamishcruden/)

:::